### ISSUE TITLE
Naming type

### ISSUE THREAD

**Issue by nemixe** [MuliaHartawan/movie-nextjs-trpc#5]
Kalau kebutuhannya untuk column, dikasi wording column juga

https://github.com/MuliaHartawan/movie-nextjs-trpc/blob/a23e22f5385893ed1f31d560c3373f948990f59b/src/app/(authenticated)/movie/_types/movie-type.ts#L1

**Comment by naufalAdib19** [comment]
done!
Sudah saya ganti
